site_name: PJM Wiki

theme:
  name: material
  features:
    - navigation.tabs
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'

# copyright
copyright: Copyright &copy; 2022 潘江明

# condition
nav:
  - Welcome: index.md
  - Linux:
    - 配置vim: linux/vimrc.md
  - 关于:
    - 关于作者: about/aboutme.md
    - 关于PJM Wiki: about/aboutwiki.md


# extra
extra:
  search:
    language: 'jp'


# Latex
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

