# Project information
site_name: PJM Wiki
site_description: PJM Wiki 是一个计算机知识整合的站点
site_author: 潘江明
site_url: https://pjimming.github.io/PJM-Wiki/
strict: false

# Repository
repo_name: 'pjimming/PJM-Wiki'
repo_url: 'https://github.com/pjimming/PJM-Wiki'

theme:
  name: material
  features:
    - navigation.tabs
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'

# copyright
copyright: Copyright &copy; 2022 潘江明

# condition
nav:
  - Welcome: index.md
  - Linux:
    - 配置vim: linux/vimrc.md
  - 关于:
    - 关于作者: about/aboutme.md
    - 关于PJM Wiki: about/aboutwiki.md


# extra
extra:
  search:
    language: 'jp'


# Latex
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

