# Project information
site_name: PJM Wiki
site_description: PJM Wiki 是一个计算机知识整合的站点
site_author: 潘江明
site_url: https://pjimming.github.io/PJM-Wiki/
strict: false

# Repository
repo_name: 'pjimming/PJM-Wiki'
repo_url: 'https://github.com/pjimming/PJM-Wiki'

theme:
  name: material
  features:
    - navigation.tabs
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'red'
  favicon: img/favicon.png
  icon:
    logo: material/library

# copyright
copyright: Copyright &copy; 2022 潘江明

# condition
nav:
  - Welcome: index.md
  - Linux:
    - 常用文件管理命令: linux/command.md
    - tmux和vim: linux/tmux_and_vim.md
    - Shell:
      - 概论: linux/shell/概论.md
      - 注释: linux/shell/注释.md
      - 变量: linux/shell/变量.md
      - 默认变量: linux/shell/默认变量.md
      - 数组: linux/shell/数组.md
      - expr命令: linux/shell/expr命令.md
      - read命令: linux/shell/read命令.md
      - echo命令: linux/shell/echo命令.md
      - printf命令: linux/shell/printf命令.md
      - test命令与判断符号[]: linux/shell/test命令与判断符号[].md
      - 判断语句: linux/shell/判断语句.md
      - 循环语句: linux/shell/循环语句.md
      - 函数: linux/shell/函数.md
      - exit命令: linux/shell/exit命令.md
      - 文件重定向: linux/shell/文件重定向.md
      - 引入外部脚本: linux/shell/引入外部脚本.md
    - git: linux/git.md
    - 管道: linux/conduit.md
    - 环境变量: linux/environment_variable.md
  - Leetcode: leetcode/index.md
  - 关于:
    - 关于作者: about/aboutme.md
    - 关于PJM Wiki: about/aboutwiki.md


# extra
extra:
  search:
    language: 'jp'


# Latex
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

