# Project information
site_name: PJM Wiki
site_description: PJM Wiki 是一个计算机知识整合的站点
site_author: 潘江明
site_url: 'https://wiki.pjmcode.top/'
strict: false

# Repository
repo_name: 'pjimming/PJM-Wiki'
repo_url: 'https://github.com/pjimming/PJM-Wiki'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  favicon: img/favicon.png
  icon:
    logo: material/library

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to light mode

# copyright
copyright: Copyright &copy; 2022 <a href="https://pjmcode.top" target="_blank" rel="noopener noreferrer">潘江明</a>

# condition
nav:
  - Welcome: 
    - Welcome: index.md
    - 我的算法竞赛之路: acm/acm.md
  - Linux:
    - WSL2的安装和使用: linux/first_work.md
    - 常用文件管理命令: linux/command.md
    - tmux和vim: linux/tmux_and_vim.md
    - Shell:
      - 概论: linux/shell/概论.md
      - 注释: linux/shell/注释.md
      - 变量: linux/shell/变量.md
      - 默认变量: linux/shell/默认变量.md
      - 数组: linux/shell/数组.md
      - expr命令: linux/shell/expr命令.md
      - read命令: linux/shell/read命令.md
      - echo命令: linux/shell/echo命令.md
      - printf命令: linux/shell/printf命令.md
      - test命令与判断符号[]: linux/shell/test命令与判断符号[].md
      - 判断语句: linux/shell/判断语句.md
      - 循环语句: linux/shell/循环语句.md
      - 函数: linux/shell/函数.md
      - exit命令: linux/shell/exit命令.md
      - 文件重定向: linux/shell/文件重定向.md
      - 引入外部脚本: linux/shell/引入外部脚本.md
    - git: linux/git.md
    - 管道: linux/conduit.md
    - 环境变量: linux/environment_variable.md
    - 常用命令: linux/common_commond.md
  - Algorithm:
    - leetcode:
      - 1. 两数之和: algorithm/leetcode/1.md
      - 21. 合并两个有序链表: algorithm/leetcode/21.md
      - 61. 旋转链表: algorithm/leetcode/61.md
      - 73. 矩阵置零: algorithm/leetcode/73.md
      - 82. 删除排序链表中的重复元素 II: algorithm/leetcode/82.md
      - 94. 二叉树的中序遍历: algorithm/leetcode/94.md
      - 150. 逆波兰表达式求值: algorithm/leetcode/150.md
      - 173. 二叉搜索树迭代器: algorithm/leetcode/173.md
      - 190. 颠倒二进制位: algorithm/leetcode/190.md
      - 191. 位1的个数: algorithm/leetcode/191.md
      - 206. 反转链表: algorithm/leetcode/206.md
      - 223. 矩形面积: algorithm/leetcode/223.md
      - 341. 扁平化嵌套列表迭代器: algorithm/leetcode/341.md
      - 456. 132 模式: algorithm/leetcode/456.md
      - 713. 乘积小于K的子数组: algorithm/leetcode/713.md
      - 1011. 在 D 天内送达包裹的能力: algorithm/leetcode/1011.md
      - 1143. 最长公共子序列: algorithm/leetcode/1143.md
      - 1603. 设计停车系统: algorithm/leetcode/1603.md
    - 剑指offer:
      - 03. 数组中重复的数字: algorithm/offer/3.md
      - 22. 链表中倒数第k个节点: algorithm/offer/22.md
      - 24. 反转链表: algorithm/offer/24.md
      - 25. 合并两个排序的链表: algorithm/offer/25.md
      - 65. 不用加减乘除做加法: algorithm/offer/65.md
    - 剑指offer Ⅱ:
      - 053. 二叉搜索树中的中序后继: algorithm/offer2/53.md
    - 程序员面试金典:
      - 17.21. 直方图的水量: algorithm/mst/17_21.md
    - My Problem:
      - 方毓乔买咖啡: algorithm/myproblem/fyqbuycoffee.md
      - 二叉树可以维护逆序对吗？: algorithm/myproblem/numofnxd.md
      - 一个简单的计算题: algorithm/myproblem/easycalculate.md
  - 动态规划:
    - 背包问题:
      - 背包模板: algorithm/bag/1.md
    - 数字三角形模型:
      - 摘花生: dp/triangle/1.md
      - 最低通行费: dp/triangle/2.md
      - 方格取数: dp/triangle/3.md
      - 传纸条: dp/triangle/4.md
  - 数据结构:
    - 并查集:
      - 并查集简介: algorithm/dsu/1.md
      - 程序自动分析(NOI2015): algorithm/dsu/2.md
      - 星球大战(JSOI2008): algorithm/dsu/3.md
      - 银河英雄传说(NOI2002): algorithm/dsu/4.md
      - 食物链(NOI2001): algorithm/dsu/5.md
    - 树状数组:
      - 树状数组简介: algorithm/bit/1.md
      - 【模板】树状数组1(单点修改，区间查询): algorithm/bit/2.md
      - 【模板】树状数组2(区间修改，单点查询): algorithm/bit/3.md
      - 逆序对: algorithm/bit/4.md
      - 火柴排队(NOIP2013 提高组): algorithm/bit/5.md
      - 配对统计(GZOI2017): algorithm/bit/6.md
    - 线段树:
      - 线段树简介: algorithm/segmentTree/1.md
      - 最大数(单点修改，区间查询): algorithm/segmentTree/2.md
      - Bin Packing Problem(单点修改，区间查询): algorithm/segmentTree/4.md
      - Can you answer these queries III(单点修改，区间查询): algorithm/segmentTree/3.md
      - Interval GCD(单点修改，区间查询): algorithm/segmentTree/5.md
      - 【模板】线段树1(区间修改，区间查询): algorithm/segmentTree/6.md
      - 【模板】线段树2(区间修改，区间查询): algorithm/segmentTree/7.md
  - 数论:
    - 数学基础知识: algorithm/math/1.md
    - 欧拉函数:
      - 欧拉函数基础: algorithm/math/euler/1.md
  - Java:
    - JavaSE:
      - Java语法规范: java/javase/JavaSE笔记（一）.md
      - Java对象和多态 （面向对象）: java/javase/JavaSE笔记（二）.md
      - Java异常机制: java/javase/JavaSE笔记（三）.md
      - Java泛型与集合类: java/javase/JavaSE笔记（四）.md
      - Java I/O: java/javase/JavaSE笔记（五）.md
      - Java多线程: java/javase/JavaSE笔记（六）.md
      - Java反射和注解: java/javase/JavaSE笔记（七）.md
    - JavaWeb:
      - Java网络编程: java/web/JavaWeb笔记（一）.md
      - 数据库基础: java/web/JavaWeb笔记（二）.md
      - Java与数据库: java/web/JavaWeb笔记（三）.md
      - 前端基础: java/web/JavaWeb笔记（四）.md
      - JavaWeb后端: java/web/JavaWeb笔记（五）.md
    - JavaSSM:
      - Spring框架技术: java/ssm/JavaSSM笔记（一）.md
      - SpringMVC: java/ssm/JavaSSM笔记（二）.md
      - SpringSecurity: java/ssm/JavaSSM笔记（三）.md
      - MySQL高级: java/ssm/JavaSSM笔记（四）.md
    - SpringBoot:
      - SpringBoot一站式开发: java/sb/SpringBoot笔记（一）.md
      - Git版本控制: java/sb/SpringBoot笔记（二）.md
      - Redis数据库: java/sb/SpringBoot笔记（三）.md
      - SpringBoot其他框架: java/sb/SpringBoot笔记（四）.md
      - Linux操作系统与项目部署: java/sb/SpringBoot笔记（五）.md
    - JVM虚拟机:
      - 走进JVM: java/jvm/JVM笔记（一）.md
      - JVM内存管理: java/jvm/JVM笔记（二）.md
      - 类与加载类: java/jvm/JVM笔记（三）.md
    - JUC并发编程:
      - 再谈多线程: java/juc/JUC笔记（一）.md
      - 多线程编程核心: java/juc/JUC笔记（二）.md
      - 并发编程进阶: java/juc/JUC笔记（三）.md
    - 鸣谢: java/index.md
  - WEB:
    - HTML基础标签:
      - HTML文件结构: web/html/1.md
      - 文本标签: web/html/2.md
      - 图片: web/html/3.md
      - 音频与视频: web/html/4.md
      - 超链接: web/html/5.md
      - 表单: web/html/6.md
      - 列表: web/html/7.md
      - 表格: web/html/8.md
      - 语义标签: web/html/9.md
      - 特殊符号: web/html/10.md
    - CSS:
      - 样式定义方式: web/css/1.md
      - 选择器: web/css/2.md
      - 颜色: web/css/3.md
      - 文本: web/css/4.md
      - 字体: web/css/5.md
      - 背景: web/css/6.md
      - 边框: web/css/7.md
      - 元素展示格式: web/css/8.md
      - 内边距与外边距: web/css/9.md
      - 盒子模型: web/css/10.md
      - 位置: web/css/11.md
      - 浮动: web/css/12.md
      - flex布局: web/css/13.md
      - 响应式布局: web/css/14.md
  - LaTeX:
    - 基础语法: latex/basic.md
    - 函数、符号及特殊字符: latex/symbols.md
    - 矩阵、条件表达式、方程组: latex/env.md
    - 字体: latex/font.md
    - 外部链接: latex/links.md
    - 颜色: latex/colors.md
  - 工具:
    - OJ生成数据模板: tools/1.md
    - 出题模板: tools/2.md
    - leetcode题解模板: tools/3.md
  - 关于:
    - 关于作者: about/aboutme.md
    - 关于PJM Wiki: about/aboutwiki.md




# extra
extra:
  search:
    language: 'jp'


# md extrc
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - '_static/js/extra.js?v=16'

extra_css:
  - '_static/css/extra.css?v=13'