# Project information
site_name: PJM Wiki
site_description: PJM Wiki 是一个计算机知识整合的站点
site_author: 潘江明
site_url: 'https://wiki.pjmcode.top/'
strict: false

# Repository
repo_name: 'pjimming/PJM-Wiki'
repo_url: 'https://github.com/pjimming/PJM-Wiki'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  favicon: img/favicon.png
  icon:
    logo: material/library

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode

# copyright
copyright: Copyright &copy; 2022 <a href="https://pjmcode.top" target="_blank" rel="noopener noreferrer">潘江明</a>

# condition
nav:
  - Welcome: index.md
  - Linux:
    - WSL2的安装和使用: linux/first_work.md
    - 常用文件管理命令: linux/command.md
    - tmux和vim: linux/tmux_and_vim.md
    - Shell:
      - 概论: linux/shell/概论.md
      - 注释: linux/shell/注释.md
      - 变量: linux/shell/变量.md
      - 默认变量: linux/shell/默认变量.md
      - 数组: linux/shell/数组.md
      - expr命令: linux/shell/expr命令.md
      - read命令: linux/shell/read命令.md
      - echo命令: linux/shell/echo命令.md
      - printf命令: linux/shell/printf命令.md
      - test命令与判断符号[]: linux/shell/test命令与判断符号[].md
      - 判断语句: linux/shell/判断语句.md
      - 循环语句: linux/shell/循环语句.md
      - 函数: linux/shell/函数.md
      - exit命令: linux/shell/exit命令.md
      - 文件重定向: linux/shell/文件重定向.md
      - 引入外部脚本: linux/shell/引入外部脚本.md
    - git: linux/git.md
    - 管道: linux/conduit.md
    - 环境变量: linux/environment_variable.md
    - 常用命令: linux/common_commond.md
  - Algorithm:
    - leetcode:
      - 1. 两数之和: algorithm/leetcode/1.md
      - 73. 矩阵置零: algorithm/leetcode/73.md
      - 150. 逆波兰表达式求值: algorithm/leetcode/150.md
      - 191. 位1的个数: algorithm/leetcode/191.md
      - 206. 反转链表: algorithm/leetcode/206.md
      - 223. 矩形面积: algorithm/leetcode/223.md
      - 341. 扁平化嵌套列表迭代器: algorithm/leetcode/341.md
      - 456. 132 模式: algorithm/leetcode/456.md
      - 1603. 设计停车系统: algorithm/leetcode/1603.md
    - 剑指offer:
      - 03. 数组中重复的数字: algorithm/offer/3.md
      - 24. 反转链表: algorithm/offer/24.md
      - 65. 不用加减乘除做加法: algorithm/offer/65.md
  - Java:
    - Java 前言: java/index.md
    - JavaSE:
      - Java语法规范: java/javase/JavaSE笔记（一）.md
      - Java对象和多态 （面向对象）: java/javase/JavaSE笔记（二）.md
      - Java异常机制: java/javase/JavaSE笔记（三）.md
      - Java泛型与集合类: java/javase/JavaSE笔记（四）.md
      - Java I/O: java/javase/JavaSE笔记（五）.md
      - Java多线程: java/javase/JavaSE笔记（六）.md
      - Java反射和注解: java/javase/JavaSE笔记（七）.md
  - 关于:
    - 关于作者: about/aboutme.md
    - 关于PJM Wiki: about/aboutwiki.md




# extra
extra:
  search:
    language: 'jp'


# md extrc
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

